# Site settings

title: Sam Lehman # Title of your site
email: grieve@gmail.com  # Your contant email

description: > # this means to ignore newlines until "baseurl:"
  sam I am
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lehman.space" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:     samuel  # Replace this with your Twitter username
github_username:      samlehman  # Replace this with your GitHub username
linkedin_username:    lehmansam  # Replace this with your LinkedIn username
google_plus_username: samlehman  # Replace this with your Google+ username
facebook_username:    lehman  # Replace this with your Facebook username

# Build settings
markdown: kramdown

include: [".well-known"]
